// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrnnifwnudnjdscxccfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJybm5pZndudWRuamRzY3hjY2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTM5MTQsImV4cCI6MjA2MDE4OTkxNH0.cFYt11Grdu0kVphp2E46-AfC_BsAWgYTxaSLV0L0yPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);